dataset: cw
exp: baseline
aggregator: null
data_seed: 1
graph_order: null
top_k: null
graph_path: null  
batch_size: 10
train_ratio: 0.8
num_workers: 8
pin_memory: False
k_fold: 5
num_graphs: 1

kernel_size: 125
stride: 2
reg_const: 0.0004
hidden_size: 16
out_size: 5

geo_feat: True
window: 1000
conv_type: gcn
num_heads: null 

optimizer: rmsprop
lr: 0.0004
gpus: 1
patience: 10
epochs: 100
log_every_n_steps: 5

cheb_k: null
embed_dim: null
